env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  main: main.go
brews:
  - description: "find-guardduty-user is used to search CloudTrial to find users that triggered GuardDuty alerts."
    github:
      owner: trussworks
      name: homebrew-tap
    homepage: "https://github.com/trussworks/find-guardduty-user"
    commit_author:
      name: trussworks-infra
      email: infra+github@truss.works
dockers:
  -
    binaries:
      - find-guardduty-user
    image_templates:
      - "trussworks/find-guardduty-user:{{ .Tag }}"
    skip_push: true
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
