version: 2.1

references:
  circleci-docker-primary: &circleci-docker-primary trussworks/circleci-docker-primary:385c300cc218b910b6fd2da8041fe848001cecf4

jobs:
  validate:
    docker:
      - image: *circleci-docker-primary
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make release
      - persist_to_workspace:
          root: /home/circleci/project/artifacts
          paths:
            - ./*
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /home/circleci/project/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(/home/circleci/project/bin/find-guardduty-user version)
            # ghr -token ${GITHUB_TOKEN} -owner ${CIRCLE_PROJECT_USERNAME} -repository ${CIRCLE_PROJECT_REPONAME} -commitish ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2.1
  main:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            tags:
              only: cg_release_pipeline
              # only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            # branches:
            #   ignore: /.*/
            tags:
              only: cg_release_pipeline
              # only: /^\d+\.\d+\.\d+$/
