version: 2.1

references:
  circleci-docker-primary: &circleci-docker-primary trussworks/circleci-docker-primary:385c300cc218b910b6fd2da8041fe848001cecf4

jobs:
  validate:
    docker:
      - image: *circleci-docker-primary
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
  release:
    docker:
      - image: *circleci-docker-primary
    steps:
      - checkout
      # - setup_remote_docker
      - run:
          name: Run goreleaser
          command: goreleaser --debug
      # - run: curl -sL https://git.io/goreleaser | bash
      # - run:
      #     name: Login to Docker Hub
      #     command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # - run:
      #     name: Check Docker container
      #     command: docker run -it trussworks/find-guardduty-user:<< pipeline.git.tag >> --help
      # - run:
      #     name: Docker push
      #     command: docker push trussworks/find-guardduty-user:<< pipeline.git.tag >>
workflows:
  version: 2.1
  validate:
    jobs:
      - validate
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
