name: validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: trussworks/shared-actions/.github/workflows/validate-go.yml@aae5a2c52d67c27a1ab11c348c4460ae09f21375 # v0.0.6
    with:
      go-version: "1.23.5"
